### PR TITLE
add check for urls key in google provider. fixes #11

### LINKED ISSUE #11: Missing hash key urls
In the google provider, there's a line:
```
json["urls"].as_a.each do |url|
```

I setup my scope authorization to just be "profile email", and it tanks on this line at the callback. Inspecting the `json` at that point only has profile and email info, but no mention of a `urls` key.

### PR DESCRIPTION
**Pull request by jwoertink**
If the `json` response has the `urls` key, it will add it in, otherwise just skip it.

### CODE REVIEW

**Comment by jwoertink** [comment]
Yeah, I can take a look at the specs. Those failing specs are unrelated to this PR though. Do you care if they're lumped in?

**Comment by jwoertink** [comment]
hmm.. Actually, I'm a little confused on this one.

```
Missing hash key: HTTP::Headers::Key(@name="Host") (KeyError)
from spec/providers/twitter_spec.cr:31:7 in '->'
```

I added a Host header in to the stub similar to the google spec has, but that didn't do anything. It seems the error might be more with the `OAuth::Consumer`. I went down the rabbit hole [starting here](https://github.com/msa7/multi_auth/blob/master/src/multi_auth/providers/twitter.cr#L3) to [here](https://github.com/crystal-lang/crystal/blob/master/src/oauth/consumer.cr#L75) 

I'm not sure if this is a crystal issue or not.

**Comment by emq** [comment]
Hi @jwoertink, if I recall it was related do `webmock.cr` and Crystal 0.26.0 🤔  can you maybe try bumping version? 🙏

**Comment by emq** [comment]
Strange, I could swear I had exact same issue somewhere in my toy-app related to webmock, but maybe I'm just randomly passing blame here 😅 Will try to cross check and report back 🙊

**Comment by emq** [comment]
So I revisited my old toy project and the exact same issue (also related to stubbing calls to twitter's API) is still there it seems ;)

It seems very similar issue was fixed in webmock.cr via https://github.com/manastech/webmock.cr/pull/25

But that line:

https://github.com/manastech/webmock.cr/blob/v0.10.0/src/webmock/core_ext.cr#L12

Should happen before `run_before_request_callbacks` as [signature that requires host header](https://github.com/crystal-lang/crystal/blob/0.26.1/src/oauth/signature.cr#L92) is [added as before callback](https://github.com/crystal-lang/crystal/blob/0.26.1/src/oauth/oauth.cr#L43) to our http client (godda@#$* callbacks).

_I'm guessing_ fix should happen within `webmock.cr`, but I'm not like 100% sure - that thing broke around Crystal 0.26.x afaik 😕 

/cc @jwoertink

**Comment by jwoertink** [comment]
Yeah, as I was digging around, that was my guess too. I'm gonna check it out once 0.27 is on homebrew and see if it's still doing it.

**Comment by msa7** [comment]
sorry for delay. Specs should be fixed in master. Could you please rebase

**Comment by jwoertink** [comment]
updated

**Pull request merged**
